title: Mario Lamacchia
email: mariolamacchia@gmail.com
description: >
  Frontend Developer at November Five, Antwerp.
baseurl: ""
url: "https://mariolamacchia.github.io"
social_links:
  github: "https://github.com/mariolamacchia"
  linkedin: "https://be.linkedin.com/in/mario-lamacchia-44ab85b9"
  google: "https://plus.google.com/u/0/113906478236947280939/posts"
  twitter: "https://twitter.com/mario_lamacchia"
  email: "mariolamacchia@gmail.com"

# Build settings
markdown: kramdown
