title: Mario Lamacchia
email: mariolamacchia@gmail.com
description: >
  Frontend Developer at November Five, Antwerp.
baseurl: ""
url: "https://mariolamacchia.github.io"

# Build settings
markdown: kramdown
