title: Mario Lamacchia
subtitle: Frontend Developer
email: mariolamacchia@gmail.com
description: >
  Frontend Developer at November Five, Antwerp.
baseurl: ""
url: "https://mariolamacchia.github.io"
paginate: 20
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
